name: "flattener"

services:
  backend:
    build:
      context: .
      target: php82
    tty: true
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:${HOST_IP:-127.0.0.0}"
    volumes:
      - ./:/var/www/html
      - vendor:/var/www/html/vendor
      - ./docker/x-php.ini:/usr/local/etc/php/conf.d/99-php.ini
volumes:
  vendor: